<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3CDOUgT\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3CDOUgT/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container3CDOUgT.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container3CDOUgT\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container3CDOUgT\srcDevDebugProjectContainer(array(
    'container.build_hash' => '3CDOUgT',
    'container.build_id' => '48cccc19',
    'container.build_time' => 1536652457,
), __DIR__.\DIRECTORY_SEPARATOR.'Container3CDOUgT');
